### ISSUE TITLE
why network need caption_lengths as an input parameter?

### ISSUE THREAD

**Issue by SweetPotatoo** [zhenming33/RAN_torch#1]
请问是否需要将label的长度输入网络，不是需要预测的吗？
谢谢

**Comment by zhenming33** [comment]
caption length是用来控制训练的seqnence的长度的，超过这个长度的没有必要计算。predict的时候这个参数设为所有label的最大长度就可以了。label的结尾由标识符预测。

**Comment by SweetPotatoo** [comment]
> caption length是用来控制训练的seqnence的长度的，超过这个长度的没有必要计算。predict的时候这个参数设为所有label的最大长度就可以了。label的结尾由标识符预测。

感谢解答
